const searches = {
  amz: { name: 'Amazon', url: 'https://www.amazon.co.uk/s?url=search-alias=aps&field-keywords='},
  bnf: { name: 'BNF (via MedicinesComplete)', url: 'https://www.medicinescomplete.com/mc/bnf/current/search.htm?q='},
  duck: { name: 'DuckDuckGo', url: 'https://duckduckgo.com/?q='},
  giphy: { name: 'Giphy', url: 'https://giphy.com/search/'},
  gh: { name: 'GitHub', url: 'https://github.com/search?utf8=%E2%9C%93&q='},
  ggl: { name: 'Google', url: 'https://www.google.co.uk/search?q='},
  gp: { name: 'GP Notebook', url: 'https://www.gpnotebook.co.uk/simpleprocess.cfm?querystring='},
  images: { name: 'Google Images', url: 'https://www.google.com/search?tbm=isch&q='},
  maps: { name: 'Google Maps', url: 'https://www.google.com/maps?q='},
  mdn: { name: 'Mozilla Developer Network', url: 'https://mdn.io/'},
  nhs: { name: 'NHS Choices', url: 'http://www.nhs.uk/Search/?q='},
  npm: { name: 'NPM', url: 'https://www.npmjs.com/search?q='},
  pt: { name: 'Patient.info (PatientUK)', url: 'https://patient.info/search.asp?searchterm='},
  translate: { name: 'Google Translate', url: 'https://translate.google.com/?text='},
  twitter: { name: 'Twitter', url: 'https://twitter.com/search?q='},
  stack: { name: 'Stack Overflow', url: 'https://stackoverflow.com/search?q='},
  ud: { name: 'Urban Dictionary', url: 'https://www.urbandictionary.com/define.php?term='},
  wiki: { name: 'Wikipedia', url: 'https://wikipedia.org/wiki/Special:Search/'},
  wolf: { name: 'Wolfram Alpha', url: 'https://www.wolframalpha.com/input/?i='},
  yt: { name: 'YouTube', url: 'https://www.youtube.com/results?search_query='},
  tv: { name: 'Thingiverse', url: 'http://www.thingiverse.com/search?q='},
}

module.exports = searches
